default: &default
  adapter: postgresql
  encoding: unicode
  port: 5433
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: paywith_api_development

test:
  <<: *default
  database: paywith_api_test

production:
  <<: *default
  database: paywith_api_production
  username: paywith_api
  password: <%= ENV['PAYWITH_API_DATABASE_PASSWORD'] %>
